name: CI

on:
  push:
    tags: v*.*.*

jobs:
  test:
    name: Test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'src/go.mod'
          cache-dependency-path: 'src/go.sum'

      - name: Test
        run: make test

  build:
    needs: test
    name: Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ arm64, amd64, 386 ]
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'src/go.mod'
          cache-dependency-path: 'src/go.sum'

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: make build

      - run: mv dist/dsync dist/dsync_${{ matrix.os }}_${{ matrix.arch }}
      - if: ${{ matrix.os == 'windows' }}
        run: mv dist/dsync_${{ matrix.os }}_${{ matrix.arch }} dist/dsync_${{ matrix.os }}_${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v7
        with:
          name: build_${{ matrix.os }}_${{ matrix.arch }}
          path: dist/

  release:
    needs: build
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist
          pattern: build_*_*
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          name: DSync ${{ github.ref_name }}
          files: dist/*